# Install the requirements for test-coverage and create the caches
on:
  workflow_dispatch

name: test-coverage create cache

jobs:
  test-coverage-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::covr
            stan-dev/cmdstanr
          needs: coverage

      - uses: ./.github/actions/cmdstanr_cached
